/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2019-06-27 06:45:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.articles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\r\n");
      out.write("        \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"\r\n");
      out.write("      xmlns:h=\"http://xmlns.jcp.org/jsf/html\"\r\n");
      out.write("      xmlns:ui=\"http://xmlns.jcp.org/jsf/facelets\"\r\n");
      out.write("      xmlns:f=\"http://xmlns.jcp.org/jsf/core\"\r\n");
      out.write("      xmlns:p=\"http://primefaces.org/ui\">\r\n");
      out.write("<h:head>\r\n");
      out.write("    <title>CRUD example</title>\r\n");
      out.write("</h:head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h3>Article</h3>\r\n");
      out.write("<h:form>\r\n");
      out.write("\r\n");
      out.write("                <p:panel header=\"Save article\">\r\n");
      out.write("\r\n");
      out.write("                <p:panelGrid columns=\"2\" cellpadding=\"5\">\r\n");
      out.write("\r\n");
      out.write("                    <p:growl id=\"growl\" showDetail=\"true\" sticky=\"true\" />\r\n");
      out.write("\r\n");
      out.write("                    <p:outputLabel for=\"title\" value=\"Title:\" />\r\n");
      out.write("                            <h:inputText id=\"title\" value=\"#{articleBean.item.title}\"/>\r\n");
      out.write("                <br/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <p:outputLabel for=\"status\" value=\"Status:\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <p:selectOneRadio id=\"status\" value=\"#{articleBean.item.status}\" unselectable=\"true\">\r\n");
      out.write("                                <f:selectItem itemLabel=\"On sale\" itemValue=\"On sale\" />\r\n");
      out.write("                                <f:selectItem itemLabel=\"Sold\" itemValue=\"Sold\" />\r\n");
      out.write("\r\n");
      out.write("                            </p:selectOneRadio>\r\n");
      out.write("                    <br/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <p:outputLabel for=\"type\" value=\"Type:\" />\r\n");
      out.write("\r\n");
      out.write("                            <p:selectOneMenu id=\"type\" value=\"#{articleBean.item.type}\" style=\"width:125px\">\r\n");
      out.write("                                <f:selectItem itemLabel=\"Select One\" itemValue=\"\" />\r\n");
      out.write("                                <f:selectItem itemLabel=\"Food\" itemValue=\"Food\" />\r\n");
      out.write("                                <f:selectItem itemLabel=\"Furniture\" itemValue=\"Furniture\" />\r\n");
      out.write("                                <f:selectItem itemLabel=\"Clothing\" itemValue=\"Clothing\" />\r\n");
      out.write("                            </p:selectOneMenu>\r\n");
      out.write("                    <br/>\r\n");
      out.write("\r\n");
      out.write("                            <p:outputLabel for=\"location\" value=\"Location:\" />\r\n");
      out.write("\r\n");
      out.write("                            <p:inputTextarea id=\"location\" rows=\"5\" cols=\"10\" value=\"#{articleBean.item.location}\" completeMethod=\"#{articleBean.completeArea}\" queryDelay=\"750\" minQueryLength=\"4\" />\r\n");
      out.write("                    <br/>\r\n");
      out.write("                            <p:outputLabel for=\"text\" value=\"Text:\" />\r\n");
      out.write("\r\n");
      out.write("                            <h:inputTextarea id=\"text\" value=\"#{articleBean.item.text}\"/>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <h:commandButton value=\"Save\" type=\"submit\"\r\n");
      out.write("                                                 action=\"#{articleBean.save()}\"/>\r\n");
      out.write("                            </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </p:panelGrid>\r\n");
      out.write("                </p:panel>\r\n");
      out.write("</h:form>\r\n");
      out.write("<h:form>\r\n");
      out.write("    <input type=\"hidden\" name=\"_eventId\" value=\"viewWholeList\">\r\n");
      out.write("\r\n");
      out.write("    <p:panel header=\"Articles list\">\r\n");
      out.write("\r\n");
      out.write("                <p:panelGrid columns=\"2\" cellpadding=\"5\">\r\n");
      out.write("\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Article </th>\r\n");
      out.write("                           <th> Title</th>\r\n");
      out.write("                        <th>Type</th>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                    <ui:repeat value=\"#{articleBean.items}\" var=\"item\">\r\n");
      out.write("                            <p:growl id=\"growl2\" showDetail=\"true\" sticky=\"true\" />\r\n");
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>#{item.id}</td>\r\n");
      out.write("                                <td>#{item.title}</td>\r\n");
      out.write("                                <td>#{item.type}</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <h:commandLink value=\"Edit\" action=\"#{articleBean.setItem(item)}\" />\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <h:commandLink value=\"Delete\" action=\"#{articleBean.destroy(item)}\" />\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                    </ui:repeat>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                </p:panelGrid>\r\n");
      out.write("                </p:panel>\r\n");
      out.write("\r\n");
      out.write("<br/>\r\n");
      out.write("<p:commandButton value=\"View complete list\" type=\"submit\"/>\r\n");
      out.write("</h:form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
